import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

function SignedOutBackdrop() {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-4 text-center text-zinc-300">
      <p className="max-w-sm text-sm leading-relaxed">
        Sign in with Clerk to run the RAWG analytics agent and inspect its
        reasoning traces.
      </p>
      <SignInButton mode="modal">
        <button className="rounded-full bg-indigo-500 px-5 py-2 text-sm font-semibold text-white transition hover:bg-indigo-400">
          Sign In
        </button>
      </SignInButton>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen h-screen overflow-hidden`}
        >
          <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
            <div className="absolute left-[-12%] top-[-10%] h-80 w-80 rounded-3xl bg-gradient-to-br from-indigo-500/35 via-transparent to-transparent blur-3xl animate-drift-slow" />
            <div className="absolute right-[-14%] top-1/4 h-[26rem] w-[26rem] rounded-[3rem] bg-gradient-to-br from-purple-500/30 via-transparent to-transparent blur-[140px] animate-drift-slower" />
            <div className="absolute bottom-[-18%] left-1/3 h-[30rem] w-[30rem] rounded-[3rem] bg-gradient-to-br from-sky-400/28 via-transparent to-transparent blur-[150px] animate-drift-lazy" />
            <div className="absolute left-[8%] top-1/3 h-52 w-52 bg-floating-square animate-float-diagonal" />
            <div
              className="absolute right-[12%] bottom-[18%] h-44 w-44 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-12s" }}
            />
            <div
              className="absolute right-[35%] top-[12%] h-36 w-36 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-6s" }}
            />
            <div
              className="absolute left-[25%] top-[18%] h-40 w-40 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-18s" }}
            />
            <div
              className="absolute right-[22%] bottom-[28%] h-48 w-48 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-24s" }}
            />
            <div
              className="absolute left-[12%] bottom-[12%] h-44 w-44 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-30s" }}
            />
            <div
              className="absolute left-[-8%] bottom-[40%] h-56 w-56 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-9s" }}
            />
            <div
              className="absolute right-[-10%] top-[10%] h-60 w-60 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-15s" }}
            />
            <div
              className="absolute left-[4%] top-[-6%] h-48 w-48 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-3s" }}
            />
            <div
              className="absolute right-[6%] bottom-[-8%] h-52 w-52 bg-floating-square animate-float-diagonal"
              style={{ animationDelay: "-21s" }}
            />
          </div>
          <header className="relative flex h-[4.5rem] w-full items-center justify-between bg-zinc-950/85 px-10 shadow-[0_18px_50px_rgba(24,20,60,0.45)] backdrop-blur-2xl">
            <div className="text-sm font-semibold uppercase tracking-[0.4em] text-indigo-200">
              Game Stats AI
            </div>
            <div className="flex items-center gap-3 pr-4">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="rounded-full bg-indigo-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-400">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <SignedOut>
            <SignedOutBackdrop />
          </SignedOut>
          <SignedIn>{children}</SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
